<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>{{ $report->name }}</title>
    <style>
        body { color: #111827; font-family: DejaVu Sans, sans-serif; font-size: 10px; }
        .header { border-bottom: 3px solid {{ $report->branding['primary_color'] ?? '#f59e0b' }}; margin-bottom: 20px; padding-bottom: 12px; }
        .brand { color: {{ $report->branding['primary_color'] ?? '#f59e0b' }}; font-size: 22px; font-weight: bold; }
        .subtitle { color: #6b7280; margin-top: 4px; }
        table { border-collapse: collapse; width: 100%; }
        th { background: {{ $report->branding['primary_color'] ?? '#f59e0b' }}; color: #ffffff; font-weight: bold; padding: 8px; text-align: left; }
        td { border-bottom: 1px solid #e5e7eb; padding: 8px; }
        tr:nth-child(even) td { background: #f9fafb; }
        .footer { color: #6b7280; font-size: 8px; margin-top: 18px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">{{ $report->branding['title'] ?? 'SmartCRM Analytics' }}</div>
        <h1>{{ $report->name }}</h1>
        <div class="subtitle">{{ $report->branding['subtitle'] ?? 'Laporan performa bisnis' }}</div>
    </div>

    <table>
        <thead>
            <tr>
                @foreach ($data['headings'] as $heading)
                    <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($data['rows'] as $row)
                <tr>
                    @foreach ($row as $value)
                        <td>{{ $value }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($data['headings']) }}">Tidak ada data untuk filter laporan ini.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by SmartCRM on {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
